### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by XiGuaSZ** [osmcode/osm-data-validation#1]
I had git clone libosmium and osm-data-validation in the same dir.
cmake .. is ok
but make is error:

check_changeset_timestamps.cpp:75:46: error: ‘class osmium::memory::Buffer’ has no member named ‘select’  for (const auto& object : buffer.select<osmium::OSMObject>())

@joto @lonvia I modify the version of osmium,had the same errors,please help,thanks for your share.

**Comment by joto** [comment]
Looks like your libosmium version is too old. Maybe you have an older version of libosmium installed somewhere else on the system and it finds that one.

**Comment by XiGuaSZ** [comment]
@joto  I modidy the CMakeList.txt libosmium version find_package(osmium 2.12.1 REQUIRED COMPONENTS io), cmake is ok.but make also the same errors

**Comment by joto** [comment]
Remove the old version of libosmium. If you want to get this to compile with both versions on your system, you are on your own.

**Comment by XiGuaSZ** [comment]
ok,closed.
